apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "premises.fullname" . }}-nginx-conf
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "premises.name" . }}-nginx-conf
    {{- include "premises.labels" . | nindent 4 }}
data:
  default.conf: |
    server {
        listen 8000 default_server;
        listen [::]:8000 default_server;
        server_name localhost;

        root /var/www/html;

        server_tokens off;

        location / {
            proxy_set_header Host $host;

            proxy_pass http://web:10000;
            proxy_buffering off;
            proxy_redirect off;
        }
    }
