---
{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "premises.fullname" . }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.ingressClassName }}
  ingressClassName: {{ . }}
  {{- end }}
  rules:
    - host: {{ .Values.domain | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "premises.fullname" $ }}-static
                port:
                  number: 8000
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "premises.fullname" $ }}-web
                port:
                  number: 10000
          - path: /_
            pathType: Prefix
            backend:
              service:
                name: {{ include "premises.fullname" $ }}-web
                port:
                  number: 10000
          - path: /mcp
            pathType: Prefix
            backend:
              service:
                name: {{ include "premises.fullname" $ }}-mcp
                port:
                  number: 10001
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.domain | quote }}
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
{{- end }}
