---
# web
apiVersion: v1
kind: Service
metadata:
  name: {{ include "premises.fullname" . }}-web
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "premises.name" . }}-web
    {{- include "premises.labels" . | nindent 4 }}
spec:
  ports:
    - name: http
      protocol: TCP
      port: 10000
  selector:
    app.kubernetes.io/name: {{ include "premises.name" . }}-web
    {{- include "premises.selectorLabels" . | nindent 4 }}
---
# mcp
apiVersion: v1
kind: Service
metadata:
  name: {{ include "premises.fullname" . }}-mcp
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "premises.name" . }}-mcp
    {{- include "premises.labels" . | nindent 4 }}
spec:
  ports:
    - name: http
      protocol: TCP
      port: 10001
  selector:
    app.kubernetes.io/name: {{ include "premises.name" . }}-mcp
    {{- include "premises.selectorLabels" . | nindent 4 }}
---
# static
apiVersion: v1
kind: Service
metadata:
  name: {{ include "premises.fullname" . }}-static
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "premises.name" . }}-static
    {{- include "premises.labels" . | nindent 4 }}
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8000
  selector:
    app.kubernetes.io/name: {{ include "premises.name" . }}-static
    {{- include "premises.selectorLabels" . | nindent 4 }}
{{- if .Values.services.proxy.enableService }}
---
# proxy
apiVersion: v1
kind: Service
metadata:
  name: {{ include "premises.fullname" . }}-proxy
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "premises.name" . }}-proxy
    {{- include "premises.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
    - name: proxy-backend
      protocol: TCP
      port: 25530
    - name: minecraft
      protocol: TCP
      port: 25565
  selector:
    app.kubernetes.io/name: {{ include "premises.name" . }}-proxy
    {{- include "premises.selectorLabels" . | nindent 4 }}
{{- end }}
