version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    groups:
      aws-sdk-go-v2:
        applies-to: version-updates
        patterns:
          - 'github.com/aws/aws-sdk-go-v2'
          - 'github.com/aws/aws-sdk-go-v2/*'
          - 'github.com/aws/smithy-go'
      bun:
        applies-to: version-updates
        patterns:
          - 'github.com/uptrace/bun'
          - 'github.com/uptrace/bun/*'
      opentelemetry:
        applies-to: version-updates
        patterns:
          - 'go.opentelemetry.io/*'
  - package-ecosystem: npm
    directory: /controlpanel/frontend
    open-pull-requests-limit: 20
    schedule:
      interval: weekly
    groups:
      mui:
        applies-to: version-updates
        patterns:
          - '@mui/*'
      typescript-eslint:
        applies-to: version-updates
        patterns:
          - 'typescript-eslint/*'
