version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directory: /controlpanel
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /controlpanel
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directory: /exteriord
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directory: /runner
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /e2e-tests
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directory: /ostack-fake
    schedule:
      interval: weekly
