version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    groups:
      bun:
        applies-to: version-updates
        patterns:
          - 'github.com/uptrace/bun'
          - 'github.com/uptrace/bun/*'
  - package-ecosystem: npm
    directory: /controlpanel/frontend
    open-pull-requests-limit: 20
    schedule:
      interval: weekly
