version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: gomod
    directory: /home
    schedule:
      interval: daily
  - package-ecosystem: gomod
    directory: /mcmanager
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: /e2e-tests
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: /home
    schedule:
      interval: daily
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
