// Code generated by "stringer -type=Operation -output=operation_string.go"; DO NOT EDIT.

package client

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OpCreateServer-0]
	_ = x[OpListFlavorDetails-1]
	_ = x[OpGetServerDetail-2]
	_ = x[OpListServerDetails-3]
	_ = x[OpStopServer-4]
	_ = x[OpDeleteServer-5]
	_ = x[OpCreateToken-6]
	_ = x[OpListImages-7]
	_ = x[OpDeleteImage-8]
	_ = x[OpCreateBootVolume-9]
	_ = x[OpListVolumes-10]
	_ = x[OpRenameVolume-11]
	_ = x[OpSaveVolumeImage-12]
}

const _Operation_name = "OpCreateServerOpListFlavorDetailsOpGetServerDetailOpListServerDetailsOpStopServerOpDeleteServerOpCreateTokenOpListImagesOpDeleteImageOpCreateBootVolumeOpListVolumesOpRenameVolumeOpSaveVolumeImage"

var _Operation_index = [...]uint8{0, 14, 33, 50, 69, 81, 95, 108, 120, 133, 151, 164, 178, 195}

func (i Operation) String() string {
	if i < 0 || i >= Operation(len(_Operation_index)-1) {
		return "Operation(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Operation_name[_Operation_index[i]:_Operation_index[i+1]]
}
