services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspaces/premises:cached

  redis:
    image: valkey/valkey:9@sha256:3eeb09785cd61ec8e3be35f8804c8892080f3ca21934d628abc24ee4ed1698f6

  postgres:
    image: postgres:18.3@sha256:78481659c47e862334611ccdaf7c369c986b3046da9857112f3b309114a65fb4
    environment:
      POSTGRES_USER: premises
      POSTGRES_DB: premises
      POSTGRES_HOST_AUTH_METHOD: trust

  object-storage:
    image: rustfs/rustfs:1.0.0-alpha.83@sha256:1cfa82fb394a7c6a4ffc24f5333b52afee608d258503f94b37fcce5cc965c896
    environment:
      RUSTFS_VOLUMES: /data
      RUSTFS_ACCESS_KEY: premises
      RUSTFS_SECRET_KEY: password
    entrypoint: /bin/sh
    command:
      - '-c'
      - 'mkdir -p /data/premises && exec rustfs'

  grafana-lgtm:
    image: grafana/otel-lgtm:0.22.0@sha256:6903a4545a4005a5cada9d44055e96d612d465f7e6d942c272ecb20e6902dec0
