services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspaces/premises:cached

  redis:
    image: valkey/valkey:9@sha256:3eeb09785cd61ec8e3be35f8804c8892080f3ca21934d628abc24ee4ed1698f6

  postgres:
    image: postgres:18@sha256:69e8582b781cb44fa4557b98ed586fe68361e320d9b12f9707494335634f4f3d
    environment:
      POSTGRES_USER: premises
      POSTGRES_DB: premises
      POSTGRES_HOST_AUTH_METHOD: trust

  object-storage:
    image: rustfs/rustfs:1.0.0-alpha.83@sha256:1cfa82fb394a7c6a4ffc24f5333b52afee608d258503f94b37fcce5cc965c896
    environment:
      RUSTFS_VOLUMES: /data
      RUSTFS_ACCESS_KEY: premises
      RUSTFS_SECRET_KEY: password
    entrypoint: /bin/sh
    command:
      - '-c'
      - 'mkdir -p /data/premises && exec rustfs'

  grafana-lgtm:
    image: grafana/otel-lgtm:0.21.0@sha256:ab627177ef1c209f4e17261401bb6649477de739a17e69a23a419b8d91d03b2f
