services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
  redis:
    image: valkey/valkey:8
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: premises
      POSTGRES_DB: premises
      POSTGRES_HOST_AUTH_METHOD: trust
  minio:
    image: quay.io/minio/minio
    environment:
      MINIO_ACCESS_KEY: premises
      MINIO_SECRET_KEY: password
    entrypoint: /bin/bash
    command:
      - '-c'
      - 'mkdir -p /data/premises && minio server /data --console-address :9001'
  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      COLLECTOR_OTLP_ENABLED: 'true'
