services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/workspace/premises:cached
    networks:
      - external_network
      - internal_network
  redis:
    image: redis:7.2
    networks:
      - internal_network
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=premises
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=premises
    networks:
      - internal_network
  minio:
    image: quay.io/minio/minio
    environment:
      - MINIO_ACCESS_KEY=premises
      - MINIO_SECRET_KEY=password
    entrypoint: /bin/bash
    command:
      - '-c'
      - 'mkdir -p /data/premises && minio server /data --console-address :9001'
    networks:
      - internal_network

networks:
  external_network:
  internal_network:
    internal: true
