services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - ../:/workspace/premises:cached
  redis:
    image: redis:alpine
  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=premises
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=premises
  minio:
    image: quay.io/minio/minio
    environment:
      - MINIO_ACCESS_KEY=premises
      - MINIO_SECRET_KEY=password
    entrypoint: /bin/bash
    command:
      - '-c'
      - 'mkdir -p /data/premises && minio server /data --console-address :9001'
