server.modules += ( "mod_auth", "mod_proxy" )

server.document-root = "/var/www/html"

# Setting this prevents lighttpd from unnecessarily listening on :80
server.port = 8000

$SERVER["socket"] == ":8000" {
    $HTTP["url"] =~ "^(/api|/_)" {
        # Forward these URLs to the application server
        proxy.server = ( "" => ( ( "host" => "::1", "port" => 10000 ) ) )
        # Disable buffering for streaming to work properly
        server.stream-request-body = 2
        server.stream-response-body = 2
    }
    # Forward remaining to the Vite dev server
    proxy.server = ( "" => ( ( "host" => "::1", "port" => 5173 ) ) )
    # Enable support for websockets
    proxy.header = ( "upgrade" => "enable" )
}

# S3 API
$SERVER["socket"] == ":9000" {
    proxy.server = ( "" => ( ( "host" => "object-storage", "port" => 9000 ) ) )
}

# RustFS Console
$SERVER["socket"] == ":9001" {
    proxy.server = ( "" => ( ( "host" => "object-storage", "port" => 9001 ) ) )
}

# Grafana
$SERVER["socket"] == ":3000" {
    proxy.server = ( "" => ( ( "host" => "grafana-lgtm", "port" => 3000 ) ) )
}

# OpenTelemetry Collector's OTLP gRPC endpoint
$SERVER["socket"] == ":4317" {
    proxy.server = ( "" => ( ( "host" => "grafana-lgtm", "port" => 4317 ) ) )
}
