// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kofuk/premises/runner/internal/env (interfaces: EnvProvider)
//
// Generated by this command:
//
//	mockgen -destination env_mock.go -package env . EnvProvider
//

// Package env is a generated GoMock package.
package env

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockEnvProvider is a mock of EnvProvider interface.
type MockEnvProvider struct {
	ctrl     *gomock.Controller
	recorder *MockEnvProviderMockRecorder
	isgomock struct{}
}

// MockEnvProviderMockRecorder is the mock recorder for MockEnvProvider.
type MockEnvProviderMockRecorder struct {
	mock *MockEnvProvider
}

// NewMockEnvProvider creates a new mock instance.
func NewMockEnvProvider(ctrl *gomock.Controller) *MockEnvProvider {
	mock := &MockEnvProvider{ctrl: ctrl}
	mock.recorder = &MockEnvProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEnvProvider) EXPECT() *MockEnvProviderMockRecorder {
	return m.recorder
}

// GetDataPath mocks base method.
func (m *MockEnvProvider) GetDataPath(path ...string) string {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range path {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetDataPath", varargs...)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetDataPath indicates an expected call of GetDataPath.
func (mr *MockEnvProviderMockRecorder) GetDataPath(path ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDataPath", reflect.TypeOf((*MockEnvProvider)(nil).GetDataPath), path...)
}

// GetTempDir mocks base method.
func (m *MockEnvProvider) GetTempDir() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTempDir")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetTempDir indicates an expected call of GetTempDir.
func (mr *MockEnvProviderMockRecorder) GetTempDir() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTempDir", reflect.TypeOf((*MockEnvProvider)(nil).GetTempDir))
}
