name: ci
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.17'
      - name: Create fake JS assets to make build to pass
        run: |
          mkdir gen
          touch gen/foo.js
      - name: Run test
        run: go test -v ./...
