name: CI
on: push

env:
  NODE_VERSION: 20

jobs:
  test-mcmanager:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./mcmanager
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.17'
      - name: Run test
        run: go test -v ./...

  build-mcmanager:
    runs-on: ubuntu-latest
    needs:
      - test-mcmanager
      - check-home-frontend-format
      - test-home-backend
    defaults:
      run:
        working-directory: ./mcmanager
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.17'
      - name: Install Required Packages
        run: |
          set -e
          sudo apt-get update
          sudo apt-get install -y make tar xz-utils
      - name: Build
        run: make
      - name: Generate Metadata
        run: |
          echo "$(git rev-parse --short HEAD)	$(sha512sum premises-mcmanager | cut -d\  -f1)" >metadata.txt
      - name: Create Archive
        run : |
          tar -cJf premises-mcmanager.tar.xz premises-mcmanager
      - uses: google-github-actions/auth@v1
        if: github.ref_name == 'master'
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
      - uses: google-github-actions/upload-cloud-storage@v1
        if: github.ref_name == 'master'
        with:
          path: mcmanager/premises-mcmanager.tar.xz
          destination: premises-artifacts
          parent: false
          process_gcloudignore: false
      - uses: google-github-actions/upload-cloud-storage@v1
        if: github.ref_name == 'master'
        with:
          path: mcmanager/metadata.txt
          destination: premises-artifacts
          parent: false
          process_gcloudignore: false

  check-home-frontend-format:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./home
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
      - name: Check code formatted
        run: |
          set -euo pipefail
          npm ci
          npm run fmt:check

  test-home-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./home
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.17'
      - name: Run test
        run: go test -v ./...

  build-home:
    runs-on: ubuntu-latest
    needs:
      - test-mcmanager
      - check-home-frontend-format
      - test-home-backend
    defaults:
      run:
        working-directory: ./home
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: . # project root
          push: ${{ github.ref_name == 'master' }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha
