name: mcmanager
on:
  push:
    branches:
      - 'master'

defaults:
  run:
    working-directory: ./mcmanager

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.17'
      - name: Run test
        run: go test -v ./...

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.17'
      - name: Install Required Packages
        run: |
          sudo apt-get update
          sudo apt-get install -y make tar xz-utils
      - name: Build
        run: make
      - name: Generate Metadata
        run: |
          echo "$(git rev-parse --short HEAD)	$(sha512sum premises-mcmanager | cut -d\  -f1)" >meta
      - name: Create Archive
        run : |
          tar -cJf premises-mcmanager.tar.xz premises-mcmanager
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
      - name: Sign to Artifacts
        run: |
          gpg --detach-sign --armor premises-mcmanager.tar.xz
          gpg --detach-sign --armor meta
      - name: Upload Artifacts
        env:
          UPDATER_AUTH_TOKEN: ${{ secrets.UPDATER_AUTH_TOKEN }}
        run: |
          curl https://prmssupd.000webhostapp.com/ \
               -F f=@premises-mcmanager.tar.xz -F filename=premises-mcmanager.tar.xz -Fauth_token="${UPDATER_AUTH_TOKEN}"
          curl https://prmssupd.000webhostapp.com/ \
               -F f=@premises-mcmanager.tar.xz.asc -F filename=premises-mcmanager.tar.xz.asc -Fauth_token="${UPDATER_AUTH_TOKEN}"
          curl https://prmssupd.000webhostapp.com/ \
               -F f=@meta -F filename=meta -Fauth_token="${UPDATER_AUTH_TOKEN}"
          curl https://prmssupd.000webhostapp.com/ \
               -F f=@meta.asc -F filename=meta.asc -Fauth_token="${UPDATER_AUTH_TOKEN}"

