name: mcmanager
on:
  push:
    branches:
      - 'master'

defaults:
  run:
    working-directory: ./mcmanager

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.17'
      - name: Run test
        run: go test -v ./...

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.17'
      - name: Install Required Packages
        run: |
          sudo apt-get update
          sudo apt-get install -y make tar xz-utils
      - name: Build
        run: make
      - name: Generate Metadata
        run: |
          echo "$(git rev-parse --short HEAD)	$(sha512sum premises-mcmanager | cut -d\  -f1)" >metadata.txt
      - name: Create Archive
        run : |
          tar -cJf premises-mcmanager.tar.xz premises-mcmanager
      - uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
      - uses: google-github-actions/upload-cloud-storage@v1
        with:
          path: mcmanager/premises-mcmanager.tar.xz
          destination: premises-artifacts
          parent: false
      - uses: google-github-actions/upload-cloud-storage@v1
        with:
          path: mcmanager/metadata.txt
          destination: premises-artifacts
          parent: false

