# Instrumentations
otel.instrumentation.common.default-enabled=false
otel.instrumentation.log4j-appender.enabled=true
otel.instrumentation.runtime-telemetry.enabled=true

# Exporters
otel.exporter.otlp.protocol=grpc
otel.logs.exporter=otlp
otel.metrics.exporter=otlp
otel.traces.exporter=none
